version: '2'
checks:
  argument-count:
    enabled: false # handled by PMD
  complex-logic:
    enabled: true
  file-lines:
    enabled: false # handled by PMD
  method-complexity:
    enabled: false # handled by PMD
  method-count:
    enabled: false # Handled by PMD
  method-lines:
    enabled: false # Handled by PMD
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: false # Handled by PMD
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  checkstyle:
    enabled: true
    config:
      file: 'config/vogle-checkstyle.xml'
  pmd:
    enabled: true
    config:
      file: 'config/vogle-ruleset-6.7.x.xml'
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
exclude_patterns:
  - 'config/'
  - '**/dist/'
  - '**/build/'
  - '**/test/'
  - '**/integTest/'
  - '**/*.md'
