version: "2"

plugins:
  checkstyle:
    enabled: true
    config:
      file: "config/vogle-checkstyle.xml"
  pmd:
    enabled: true
    config:
      file: "config/vogle-ruleset-6.11.xml"
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
      minimum_severity: critical
      tests_patterns:
        - src/test/**
        - src/integTest/**
